# Generated by Django 6.0.5 on 2026-05-23 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('change_24h', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume_24h', models.DecimalField(decimal_places=0, max_digits=30)),
                ('market_cap', models.DecimalField(decimal_places=0, max_digits=30)),
                ('high_24h', models.DecimalField(decimal_places=4, max_digits=20)),
                ('low_24h', models.DecimalField(decimal_places=4, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='CoinChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('open', models.DecimalField(decimal_places=4, max_digits=20)),
                ('high', models.DecimalField(decimal_places=4, max_digits=20)),
                ('low', models.DecimalField(decimal_places=4, max_digits=20)),
                ('close', models.DecimalField(decimal_places=4, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=0, max_digits=30)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='trading.coin')),
            ],
            options={
                'ordering': ['time'],
                'unique_together': {('coin', 'time')},
            },
        ),
    ]
