# Generated by Django 6.0.5 on 2026-05-24 13:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_coin_coinchart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='usd_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
    ]
